//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string TypeofOccupancy { get; set; }
        public string VendorGuarantorName { get; set; }
        public string VendorGuarantorPhone { get; set; }
        public string VendorGuarantorAddress { get; set; }
        public string Town { get; set; }
        public string LandDescription { get; set; }
        public string LeaseTerm { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string LandDoc1 { get; set; }
        public string LandDoc2 { get; set; }
        public string LandDoc3 { get; set; }
        public string LandDoc4 { get; set; }
        public string LandDoc5 { get; set; }
        public Nullable<int> LandIndex { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
